#!/usr/bin/php
<?php

require 'config.php';
require FRAMEWORK.'database.php';
require FRAMEWORK.'zerdest_argv.php';
$zerdest_argv = new zerdest_argv();


//start the framework
if($argv[1] == 'start')
{
    //connection
    $DB = new database();
    $DB->connect();

    //Create the database if it is empty
    if(!empty($argv[2]))
    {
        //Create the database and add an user
        $DB->create_new_database($argv[2]);
        $DB->create_user_table($argv[2]);
        $DB->insert_default_admin();
    }

    //Create a new login controller
    $zerdest_argv->new_controller(['2'=>'login']);
    exit;
}


if($argv && $argv[1] == 'new-controller')
{  
    //Create a new controller 
    $zerdest_argv->new_controller($argv);
}





    

