#!/usr/bin/php
<?php

require 'config.php';
require FRAMEWORK.'database.php';
require FRAMEWORK.'zerdest_argv.php';
$zerdest_argv = new zerdest_argv();


//frameworkü başlat
if($argv[1] == 'start')
{
    //Bağlan
    $DB = new database();
    $DB->connect();

    //Boş değilse database'i kur
    if(!empty($argv[2]))
    {
        //Database oluşr ve kullanıcı ekle
        $DB->create_new_database($argv[2]);
        $DB->create_user_table($argv[2]);
        $DB->insert_default_admin();
    }

    //Yeni login controller oluştur
    $zerdest_argv->new_controller(['2'=>'login']);

    exit;
}


if($argv && $argv[1] == 'new-controller')
{  
    //Yeni bir controller oluştur
    $zerdest_argv->new_controller($argv);
}





    

