#!/usr/bin/php
<?php

require 'config.php';
require_once __DIR__ . '/vendor/autoload.php';
use framework\zerdest_command;

$zerdest = new zerdest_command();


//start the framework
if($argv[1] == 'start')
{
    //connection
    $DB = new database();
    $DB->connect();

    //Create the database if it is empty
    if(!empty($argv[2]))
    {
        //Create the database and add an user
        $DB->create_new_database($argv[2]);
        $DB->create_user_table($argv[2]);
        $DB->insert_default_admin();
    }

    //Create a new login controller
    $zerdest->new_controller(['2'=>'login']);
    exit;
}


if($argv && $argv[1] == 'new-controller')
{  
    //Create a new controller 
    $zerdest->new_controller($argv);
}





    

