{{php}}

namespace app\controller;

use \framework\controller;

class {{controller_name}} extends controller
{

    public function __construct()
    {
        //parent::__construct();

    }

    public function home()
    {

      $this->render('{{controller_name}}/home'); 
    }

    public function add()
    {
        //
    }

    public function delete()
    {
        //
    }


    public function edit()
    {
        //   
    }

}