{{php}}


class {{controller_name}}_controller extends controller
{

    public function __construct()
    {
        parent::__construct();

        //Model
        $this->model->load();
    }

    public function home()
    {

      $this->render('{{controller_name}}/home'); 
    }

    public function add()
    {
        //
    }

    public function delete()
    {
        //
    }


    public function edit()
    {
        //   
    }

}